openapi: 3.0.0
info:
  title: Todo App API
  version: 1.0.0
  description: Complete CRUD API for task management with history and analytics

servers:
  - url: http://localhost:9000/api/v1
    description: Local development server

paths:
  /tasks:
    get:
      summary: List all tasks
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
    post:
      summary: Create new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'

  /tasks/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Get single task
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
    put:
      summary: Update task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
    delete:
      summary: Delete task
      responses:
        '204':
          description: Deleted

  /tasks/{id}/complete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    patch:
      summary: Mark task complete
      responses:
        '200':
          description: Completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'

  /tasks/{id}/incomplete:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
    patch:
      summary: Mark task incomplete
      responses:
        '200':
          description: Incompleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'

  /history:
    get:
      summary: Get task history
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
        - name: task_id
          in: query
          schema:
            type: string
            format: uuid
        - name: action_type
          in: query
          schema:
            type: string
            enum: [CREATED, UPDATED, COMPLETED, INCOMPLETED, DELETED]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryListResponse'

  /stats/weekly:
    get:
      summary: Get weekly statistics
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatsResponse'

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [healthy]
                  service:
                    type: string

components:
  schemas:
    Task:
      type: object
      required: [id, title, is_completed, created_at, updated_at]
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
          nullable: true
        is_completed:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        completed_at:
          type: string
          format: date-time
          nullable: true

    HistoryEntry:
      type: object
      required: [history_id, task_id, action_type, timestamp]
      properties:
        history_id:
          type: string
          format: uuid
        task_id:
          type: string
          format: uuid
        action_type:
          type: string
          enum: [CREATED, UPDATED, COMPLETED, INCOMPLETED, DELETED]
        description:
          type: string
          nullable: true
        timestamp:
          type: string
          format: date-time

    TaskStatistics:
      type: object
      required: [tasks_created_this_week, tasks_completed_this_week, total_completed, total_incomplete, week_start, week_end]
      properties:
        tasks_created_this_week:
          type: integer
        tasks_completed_this_week:
          type: integer
        total_completed:
          type: integer
        total_incomplete:
          type: integer
        week_start:
          type: string
          format: date
        week_end:
          type: string
          format: date

    CreateTaskRequest:
      type: object
      required: [title]
      properties:
        title:
          type: string
        description:
          type: string

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string

    TaskListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    TaskResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/Task'
        popup:
          type: string
          enum: [TASK_CREATED, TASK_UPDATED, TASK_COMPLETED, TASK_INCOMPLETED, TASK_DELETED]

    HistoryListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/HistoryEntry'
        pagination:
          type: object
          properties:
            page:
              type: integer
            limit:
              type: integer
            total:
              type: integer

    StatsResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          $ref: '#/components/schemas/TaskStatistics'
