#!/bin/bash
# Deploy Phase V Todo App to Azure
# Uses Terraform to provision all infrastructure

set -e  # Exit on error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Azure CLI path (Windows)
AZ_CLI="/c/Program Files/Microsoft SDKs/Azure/CLI2/wbin/az.cmd"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Phase V Todo App - Azure Deployment${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Step 1: Verify Azure CLI login
echo -e "${YELLOW}Step 1: Verifying Azure login...${NC}"
if ! "$AZ_CLI" account show &> /dev/null; then
    echo -e "${RED}❌ Not logged in to Azure${NC}"
    echo "Please run: az login"
    exit 1
fi

SUBSCRIPTION_NAME=$("$AZ_CLI" account show --query "name" -o tsv)
SUBSCRIPTION_ID=$("$AZ_CLI" account show --query "id" -o tsv)
echo -e "${GREEN}✅ Logged in to Azure${NC}"
echo "   Subscription: $SUBSCRIPTION_NAME"
echo "   ID: $SUBSCRIPTION_ID"
echo ""

# Step 2: Set configuration variables
echo -e "${YELLOW}Step 2: Configuration${NC}"

# Environment (production, staging, development)
ENVIRONMENT=${ENVIRONMENT:-"production"}

# Azure region
LOCATION=${LOCATION:-"eastus"}

# Resource group name
RESOURCE_GROUP="todo-app-${ENVIRONMENT}-rg"

# Cluster name
CLUSTER_NAME="todo-app-${ENVIRONMENT}"

echo "   Environment: $ENVIRONMENT"
echo "   Location: $LOCATION"
echo "   Resource Group: $RESOURCE_GROUP"
echo "   Cluster Name: $CLUSTER_NAME"
echo ""

# Step 3: Confirm deployment
echo -e "${YELLOW}⚠️  Warning: This will create Azure resources that incur costs${NC}"
echo ""
echo "Estimated monthly cost:"
echo "  - AKS Cluster (control plane): $0"
echo "  - AKS Nodes (3x Standard_DS2_v2): ~$100"
echo "  - Event Hubs Standard (2 TUs): $166"
echo "  - Key Vault: $0.03"
echo "  - ACR Standard: $20"
echo "  - Log Analytics: $10"
echo "  -----------------------------------------"
echo "  Total: ~$296/month"
echo ""
echo "💰 If you have Azure Free Tier ($200 credits), this is covered for 30 days!"
echo ""

read -p "Do you want to proceed with deployment? (yes/no): " CONFIRM
if [[ "$CONFIRM" != "yes" && "$CONFIRM" != "y" ]]; then
    echo -e "${RED}Deployment cancelled${NC}"
    exit 0
fi
echo ""

# Step 4: Create Resource Group
echo -e "${YELLOW}Step 3: Creating Resource Group...${NC}"
if "$AZ_CLI" group show --name "$RESOURCE_GROUP" &> /dev/null; then
    echo -e "${GREEN}✅ Resource group already exists${NC}"
else
    "$AZ_CLI" group create \
        --name "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --tags "Environment=$ENVIRONMENT" "Project=TodoApp-Phase5" "ManagedBy=Terraform"
    echo -e "${GREEN}✅ Resource group created${NC}"
fi
echo ""

# Step 5: Configure Terraform Backend
echo -e "${YELLOW}Step 4: Setting up Terraform backend (Azure Blob Storage)...${NC}"

# Storage account for Terraform state
STORAGE_ACCOUNT="todoappterraform$(echo $RANDOM | md5sum | head -c 8)"
CONTAINER_NAME="tfstate"

if ! "$AZ_CLI" storage account show --name "$STORAGE_ACCOUNT" --resource-group "$RESOURCE_GROUP" &> /dev/null; then
    echo "   Creating storage account: $STORAGE_ACCOUNT"
    "$AZ_CLI" storage account create \
        --name "$STORAGE_ACCOUNT" \
        --resource-group "$RESOURCE_GROUP" \
        --location "$LOCATION" \
        --sku Standard_LRS \
        --encryption-services blob \
        --tags "Purpose=TerraformState"

    # Get storage account key
    ACCOUNT_KEY=$("$AZ_CLI" storage account keys list \
        --resource-group "$RESOURCE_GROUP" \
        --account-name "$STORAGE_ACCOUNT" \
        --query '[0].value' -o tsv)

    # Create container
    "$AZ_CLI" storage container create \
        --name "$CONTAINER_NAME" \
        --account-name "$STORAGE_ACCOUNT" \
        --account-key "$ACCOUNT_KEY"

    echo -e "${GREEN}✅ Terraform backend storage created${NC}"
else
    echo -e "${GREEN}✅ Terraform backend storage already exists${NC}"
fi
echo ""

# Step 6: Initialize Terraform
echo -e "${YELLOW}Step 5: Initializing Terraform...${NC}"
cd ../terraform/aks

# Create backend configuration
cat > backend-config.hcl <<EOF
resource_group_name  = "$RESOURCE_GROUP"
storage_account_name = "$STORAGE_ACCOUNT"
container_name       = "$CONTAINER_NAME"
key                  = "phase5-${ENVIRONMENT}.tfstate"
EOF

# Initialize Terraform with backend
terraform init -backend-config=backend-config.hcl

echo -e "${GREEN}✅ Terraform initialized${NC}"
echo ""

# Step 7: Create Terraform variables file
echo -e "${YELLOW}Step 6: Creating Terraform variables...${NC}"

cat > terraform.tfvars <<EOF
# Phase V Todo App - Terraform Variables
# Generated by deploy-to-azure.sh

environment         = "$ENVIRONMENT"
location            = "$LOCATION"
resource_group_name = "$RESOURCE_GROUP"
cluster_name        = "$CLUSTER_NAME"

# AKS Configuration
kubernetes_version  = "1.29.0"
availability_zones  = ["1", "2", "3"]

# System Node Pool
system_node_count     = 3
system_node_min_count = 3
system_node_max_count = 6
system_node_vm_size   = "Standard_DS2_v2"  # 2 vCPU, 7GB RAM

# Application Node Pool
app_node_count     = 3
app_node_min_count = 3
app_node_max_count = 12
app_node_vm_size   = "Standard_DS3_v2"  # 4 vCPU, 14GB RAM

# Monitoring Node Pool
monitoring_node_count     = 2
monitoring_node_min_count = 2
monitoring_node_max_count = 4
monitoring_node_vm_size   = "Standard_DS2_v2"  # 2 vCPU, 7GB RAM

# Azure Container Registry
acr_sku = "Standard"

# Event Hubs (Kafka)
eventhubs_capacity = 2  # 2 throughput units

# Monitoring
log_retention_days = 30

# Tags
common_tags = {
  Environment = "$ENVIRONMENT"
  Project     = "TodoApp-Phase5"
  ManagedBy   = "Terraform"
  Owner       = "$(whoami)"
}
EOF

echo -e "${GREEN}✅ Terraform variables created${NC}"
echo ""

# Step 8: Terraform Plan
echo -e "${YELLOW}Step 7: Running Terraform plan...${NC}"
terraform plan -out=tfplan

echo ""
echo -e "${GREEN}✅ Terraform plan completed${NC}"
echo ""

# Step 9: Confirm apply
echo -e "${YELLOW}⚠️  Ready to apply Terraform plan${NC}"
echo ""
read -p "Do you want to apply the Terraform plan and create resources? (yes/no): " APPLY_CONFIRM
if [[ "$APPLY_CONFIRM" != "yes" && "$APPLY_CONFIRM" != "y" ]]; then
    echo -e "${RED}Deployment cancelled. Terraform plan saved to: tfplan${NC}"
    exit 0
fi
echo ""

# Step 10: Terraform Apply
echo -e "${YELLOW}Step 8: Applying Terraform plan (this may take 15-20 minutes)...${NC}"
terraform apply tfplan

echo ""
echo -e "${GREEN}✅ Infrastructure provisioned successfully!${NC}"
echo ""

# Step 11: Get outputs
echo -e "${YELLOW}Step 9: Retrieving deployment information...${NC}"
echo ""

AKS_NAME=$(terraform output -raw cluster_name)
ACR_NAME=$(terraform output -raw acr_name)
EVENTHUBS_ENDPOINT=$(terraform output -raw eventhubs_kafka_endpoint)
KEY_VAULT_NAME=$(terraform output -raw key_vault_name)

echo -e "${GREEN}Deployment Complete!${NC}"
echo ""
echo "========================================="
echo "Resource Details:"
echo "========================================="
echo "Resource Group:    $RESOURCE_GROUP"
echo "AKS Cluster:       $AKS_NAME"
echo "ACR:               $ACR_NAME"
echo "Event Hubs:        $EVENTHUBS_ENDPOINT"
echo "Key Vault:         $KEY_VAULT_NAME"
echo ""
echo "========================================="
echo "Next Steps:"
echo "========================================="
echo ""
echo "1. Get AKS credentials:"
echo "   az aks get-credentials --resource-group $RESOURCE_GROUP --name $AKS_NAME"
echo ""
echo "2. Verify cluster access:"
echo "   kubectl get nodes"
echo ""
echo "3. Deploy Dapr to AKS:"
echo "   dapr init --kubernetes"
echo ""
echo "4. Deploy the application:"
echo "   helm upgrade --install todo-app ../../../helm/todo-app \\"
echo "     -f ../../../helm/todo-app/values-aks.yaml \\"
echo "     --namespace todo-app-prod \\"
echo "     --create-namespace"
echo ""
echo "5. Verify deployment:"
echo "   kubectl get pods -n todo-app-prod"
echo ""
echo "========================================="
echo ""
echo -e "${GREEN}✅ Phase V infrastructure is ready!${NC}"
echo ""
echo "💡 Tip: Check costs at: https://portal.azure.com/#view/Microsoft_Azure_CostManagement"
echo ""
