# Kubernetes Secret for Sensitive Configuration
# IMPORTANT: This is a TEMPLATE file
# DO NOT commit actual secrets to version control
#
# For production deployment:
# 1. Copy this file to `secret.yaml` (add to .gitignore)
# 2. Replace <BASE64_ENCODED_VALUE> with actual base64-encoded secrets
# 3. Apply with: kubectl apply -f secret.yaml
#
# To base64 encode a value: echo -n "your-secret-value" | base64
# To base64 decode a value: echo "encoded-value" | base64 -d

apiVersion: v1
kind: Secret
metadata:
  name: todo-secrets
  labels:
    app: todo-app
type: Opaque
data:
  # PostgreSQL connection string (Neon)
  # Example: postgresql://user:password@host:5432/dbname?sslmode=require
  database-url: <BASE64_ENCODED_DATABASE_URL>

  # OpenAI API Key (or other LLM provider)
  # Example: sk-proj-xxxxxxxxxxxxxxxxxxxxx
  openai-api-key: <BASE64_ENCODED_OPENAI_API_KEY>

  # Better Auth Shared Secret (must match frontend)
  # Example: 32-character random string
  better-auth-secret: <BASE64_ENCODED_BETTER_AUTH_SECRET>

---
# Development example (DO NOT use in production):
# apiVersion: v1
# kind: Secret
# metadata:
#   name: todo-secrets
#   labels:
#     app: todo-app
# type: Opaque
# stringData:  # Use stringData for plain text (auto-encoded)
#   database-url: "postgresql://user:pass@localhost:5432/todo_dev"
#   openai-api-key: "sk-test-key"
#   better-auth-secret: "dev-secret-32-characters-long-!"
