# Dapr Secrets Component
# Local: Kubernetes Secrets | Production: Azure Key Vault

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  # Local environment (Minikube)
  {{- if eq .Values.environment "local" }}
  type: secretstores.kubernetes
  version: v1
  metadata:
  - name: vaultName
    value: default  # K8s namespace for secrets
  {{- else }}
  # Production environment (AKS)
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: "{{ .Values.azure.keyVaultName }}"
  - name: azureClientId
    value: ""  # Managed Identity (no client secret)
  {{- end }}
