openapi: 3.1.0
info:
  title: AI Chatbot API - Phase 3
  version: 1.0.0
  description: |
    Chat endpoint for AI-powered task management chatbot.
    Integrates with existing Phase 2 authentication and task management.

servers:
  - url: /api/v1
    description: API v1

paths:
  /chat:
    post:
      operationId: chatWithAgent
      summary: Send message to AI assistant
      description: |
        Stateless chat endpoint that:
        1. Loads conversation history from database
        2. Processes user message
        3. Runs AI agent with MCP tools
        4. Streams response via SSE
        5. Saves response to database
      tags:
        - Chat
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
            examples:
              newConversation:
                summary: Start new conversation
                value:
                  message: "Add a task to buy groceries"
              existingConversation:
                summary: Continue existing conversation
                value:
                  conversation_id: 123
                  message: "Show me all my tasks"
      responses:
        '200':
          description: Streaming SSE response
          content:
            text/event-stream:
              schema:
                type: string
              example: |
                data: I've added
                data:  'Buy groceries'
                data:  to your tasks!
                data: [DONE]
        '401':
          $ref: '#/components/responses/Unauthorized'
        '422':
          $ref: '#/components/responses/ValidationError'
        '503':
          $ref: '#/components/responses/ServiceUnavailable'

  /conversations:
    get:
      operationId: listConversations
      summary: List user's conversations
      description: Returns all conversations for the authenticated user
      tags:
        - Conversations
      security:
        - BearerAuth: []
      parameters:
        - name: is_active
          in: query
          schema:
            type: boolean
          description: Filter by active status
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
          description: Maximum conversations to return
      responses:
        '200':
          description: List of conversations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /conversations/{conversation_id}:
    get:
      operationId: getConversation
      summary: Get conversation details
      description: Returns conversation with message history
      tags:
        - Conversations
      security:
        - BearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Conversation details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      operationId: deleteConversation
      summary: Delete conversation
      description: Soft-deletes conversation (sets is_active=false)
      tags:
        - Conversations
      security:
        - BearerAuth: []
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Conversation deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Better Auth JWT token

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        conversation_id:
          type: integer
          nullable: true
          description: Existing conversation ID (null to create new)
          example: 123
        message:
          type: string
          minLength: 1
          maxLength: 5000
          description: User message text
          example: "Add a task to buy groceries"

    ConversationListResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationSummary'
        total:
          type: integer
          example: 5

    ConversationSummary:
      type: object
      properties:
        id:
          type: integer
          example: 123
        title:
          type: string
          example: "Conversation 2025-12-22 14:30"
        is_active:
          type: boolean
          example: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        message_count:
          type: integer
          example: 10

    ConversationResponse:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        is_active:
          type: boolean
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      properties:
        id:
          type: integer
        role:
          type: string
          enum: [user, assistant, system]
        content:
          type: string
        created_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          description: Error message
          example: "Conversation not found"

  responses:
    Unauthorized:
      description: Invalid or missing authentication
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Not authenticated"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Conversation not found"

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: array
                items:
                  type: object
                  properties:
                    loc:
                      type: array
                      items:
                        type: string
                    msg:
                      type: string
                    type:
                      type: string

    ServiceUnavailable:
      description: AI service temporarily unavailable
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "AI service rate limit exceeded. Please try again in a moment."
